[package]
name = "divans"
version = "0.0.1"
authors = [
    "Daniel Reiter Horn <danielrh@dropbox.com>",
    "Jongmin Baek <jongmin@dropbox.com>",
    "Anatoly Yakovenko <anatoly@dropbox.com>"
]
license = "BSD-3-Clause/MIT or Apache"
documentation = "tbd"
keywords = ["brotli", "decompression", "lz77", "huffman", "nostd"]
readme = "README.md"
build = "build.rs"

[[bin]]
doc = false
name = "divans"

[profile.release]
lto=true

[build-dependencies]
vergen = "0.1"

[dependencies]
"alloc-no-stdlib" = "~1.2"
#"brotli-decompressor" = "~1"
"brotli" = ">= 1.0.9"
[features]
default= []#["block_switch"]
billing = []
blend = []
debug_entropy = []
bitcmdselect = []
float64 = []
block_switch = []
seccomp = ["brotli/seccomp"]
no-stdlib = ["alloc-no-stdlib/no-stdlib", "brotli/no-stdlib"]
benchmark = ["brotli/benchmark"]
external-literal-probability = ["brotli/external-literal-probability"]

uncached_frequentist = []