[package]
name = "divans"
version = "0.0.1"
authors = ["Daniel Reiter Horn <danielrh@dropbox.com>"]
description = "An divANS decoder"
license = "BSD-3-Clause/MIT"
documentation = "tbd"
homepage = "https://github.com/dropbox/rust-divans"
repository = "https://github.com/dropbox/rust-divans"
keywords = ["brotli", "decompression", "lz77", "huffman", "nostd"]
readme = "README.md"

[[bin]]
doc = false
name = "divans"

[profile.release]
lto=true

[dependencies]
"alloc-no-stdlib" = "~1.2"
"brotli-decompressor" = "~1"

[features]
float64 = []
seccomp = ["brotli-decompressor/seccomp"]
no-stdlib = ["alloc-no-stdlib/no-stdlib", "brotli-decompressor/no-stdlib"]
benchmark = ["brotli-decompressor/benchmark"]
